### ISSUE TITLE
versions

### ISSUE THREAD

**Issue by DevRapitow** [trailbehind/lrm-Here#1]
The only version I can find is 1.0.0. The npm page lists a 1.1.0 but those download links are broken.
Is the lrm-here.js file in Dist the most up to date?

Also are you considering updating this plugin to support routing object options like live traffic?

**Comment by JesseCrocker** [comment]
Hello, and thanks for your interest in using this.
You can see a list of releases at https://github.com/trailbehind/lrm-Here/releases
It looks like the problem you ran into was due to a broken link at https://trailbehind.github.io/lrm-Here/download/  That should now be fixed.

As for adding more features, no, i have no plans on doing that, but your welcome to fork this project and add those things yourself.
